distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: DateTime-Util-Astro
no_index: 
  directory: 
    - inc
    - t
requires: 
  DateTime: 0
  DateTime::Util::Calc: 0.12
  Math::BigInt: 0
  Math::Trig: 0
  POSIX: 0
version: 0.08
