--- #YAML:1.0
name: DateTime-Util-Astro
version: 0.02
author:
  - ~
abstract: |-
  Utilities for DateTime Extensions That Require Astronomical Calculations
license: perl
requires:
  DateTime: 0
  DateTime::Util::Calc: 0.02
  Math::Trig: 0
  POSIX: 0
  Params::Validate: 0
recommends:
  perl: 5.6.1
build_requires:
  Test::More: 0
conflicts: {}
provides:
  DateTime::Util::Astro::::Location:
    file: lib/DateTime/Util/Astro/Common.pm
    version: 0.01
  DateTime::Util::Astro::Common:
    file: lib/DateTime/Util/Astro/Common.pm
    version: 0.01
  DateTime::Util::Astro::Moon:
    file: lib/DateTime/Util/Astro/Moon.pm
    version: 0.01
  DateTime::Util::Astro::Sun:
    file: lib/DateTime/Util/Astro/Sun.pm
    version: 0.02
generated_by: Module::Build version 0.22
